// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config structure
 * Place the definition of custom battle configuration structure members in this file.
 *
 * Make sure that the name you want is not already taken by looking into battle.hpp
 * Do not forget to add initilization logic to battle_config_init.inc
 *
 * Format:
 *	 <datatype> name;
 **/

	int Head_Gear_1;
	int Head_Gear_2;
	int Head_Gear_3;
	int Head_Gear_4;
	int Head_Gear_5; 
	int Head_Gear_6;
	int Head_Gear_7;
	int Head_Gear_8;
	int Head_Gear_9;
	int Head_Gear_10;
	int Armor_1;
	int Armor_2;	
	int Armor_3;
	int Armor_4;
	int Armor_5;
	int Armor_6;
	int Armor_7;
	int Armor_8;
	int Armor_9;
	int Armor_10;
	int Shield_1;
	int Shield_2;
	int Shield_3;
	int Shield_4;
	int Shield_5;
	int Shield_6;
	int Shield_7;
	int Shield_8;
	int Shield_9;
	int Shield_10;
	int Foot_Gear_1;
	int Foot_Gear_2;
	int Foot_Gear_3;
	int Foot_Gear_4;
	int Foot_Gear_5;
	int Foot_Gear_6;
	int Foot_Gear_7;
	int Foot_Gear_8;
	int Foot_Gear_9;
	int Foot_Gear_10;
	int Garment_1;
	int Garment_2;
	int Garment_3;
	int Garment_4;
	int Garment_5;
	int Garment_6;
	int Garment_7;
	int Garment_8;
	int Garment_9;
	int Garment_10;
	int Weapon_LV1_1;
	int Weapon_LV1_2;
	int Weapon_LV1_3;
	int Weapon_LV1_4;
	int Weapon_LV1_5;
	int Weapon_LV1_6;
	int Weapon_LV1_7;
	int Weapon_LV1_8;
	int Weapon_LV1_9;
	int Weapon_LV1_10;
	int Weapon_LV2_1;
	int Weapon_LV2_2;
	int Weapon_LV2_3;
	int Weapon_LV2_4;
	int Weapon_LV2_5;
	int Weapon_LV2_6;
	int Weapon_LV2_7;	
	int Weapon_LV2_8;
	int Weapon_LV2_9;
	int Weapon_LV2_10;
	int Weapon_LV3_1;
	int Weapon_LV3_2;
	int Weapon_LV3_3;
	int Weapon_LV3_4;
	int Weapon_LV3_5;
	int Weapon_LV3_6;
	int Weapon_LV3_7;
	int Weapon_LV3_8;
	int Weapon_LV3_9;
	int Weapon_LV3_10;
	int Weapon_LV4_1;
	int Weapon_LV4_2;
	int Weapon_LV4_3;
	int Weapon_LV4_4;
	int Weapon_LV4_5;
	int Weapon_LV4_6;
	int Weapon_LV4_7;
	int Weapon_LV4_8;
	int Weapon_LV4_9;
	int Weapon_LV4_10;
	int Shadow_7;
	int Shadow_8;
	int Shadow_9;
	int Shadow_10;